esphome:
  name: ${name}

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: "8.5"
  power_save_mode: high
  manual_ip:
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  ap:
    ssid: ${friendly_name}

captive_portal:
